version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_KRYSTAL_BULL_IP
      APP_PORT: 3001
  
  web:
    image: bitcoinscala/oracle-server-ui:1.9.4@sha256:7f5213536a5f98f74abba64aaa6275dbb15d94bbb98511f2c13b2b360010d2bb
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/oracleserver:/bitcoin-s
      - ${APP_DATA_DIR}/data/log:/log
    environment:
      LOG_PATH: "/log/"
      BITCOIN_S_HOME: "/bitcoin-s/"
      ORACLE_SERVER_API_URL: "http://${APP_KRYSTAL_BULL_SERVER_IP}:9998/"
      TOR_PROXY: socks5://${TOR_PROXY_IP}:${TOR_PROXY_PORT}
      DEFAULT_UI_PASSWORD: "none"
      BITCOIN_S_ORACLE_RPC_PASSWORD: $APP_PASSWORD
    networks:
      default:
        ipv4_address: $APP_KRYSTAL_BULL_IP
    depends_on: 
      - oracleserver
  
  oracleserver:
    image: bitcoinscala/bitcoin-s-oracle-server:1.9.4@sha256:844db1c6fd314dfc37d928b76e886ea124419c36f0d4e06952e35776adeabe06
    entrypoint: ["/opt/docker/bin/bitcoin-s-oracle-server", "--datadir", "/bitcoin-s", "--conf", "/opt/docker/docker-application.conf"]   
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/oracleserver:/bitcoin-s
    environment:
      BITCOIN_S_KEYMANAGER_ENTROPY: $APP_SEED
      BITCOIN_S_ORACLE_RPC_PASSWORD: $APP_PASSWORD
      DISABLE_JLINK: "1"
    networks:
      default:
        ipv4_address: $APP_KRYSTAL_BULL_SERVER_IP
